# Generated by Django 2.2.2 on 2019-06-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_auto_20190623_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='like',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='gostou'),
        ),
        migrations.AddField(
            model_name='live',
            name='unlike',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='não gostou'),
        ),
    ]
