[tool.poetry]
name = "spam"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.27.1"}
opentelemetry-distro = "^0.44b0"
opentelemetry-exporter-otlp = "^1.23.0"
httpx = "^0.27.0"
opentelemetry-instrumentation-httpx = "^0.44b0"
opentelemetry-instrumentation-logging = "^0.44b0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
