[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "meupacote-mod1"
version = "0.1"
description = "Parte 1 do namespace meupacote"

[tool.setuptools.packages.find]
where = ["."]
