[project]
name = "meupacote-mod2"
version = "0.1"
description = "Parte 2 do namespace meupacote"

[tool.setuptools.packages.find]
where = ["."]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"