[project]
name = "cotacao"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx (>=0.28.1,<0.29.0)",
    "rich (>=13.9.4,<14.0.0)",
    "cyclopts (>=3.4.0,<4.0.0)"
]

[tool.towncrier]
directory = "chanlogs.d"
filename = "CHANGELOG.md"
package = "cotacao"
title_format = "## Live 278 - [{version}](http://github.com/dunossauro/notas-musicais/releases/{version})"
issue_format = "[#{issue}](http://github.com/dunossauro/notas-musicais/issues/{issue})"


[[tool.towncrier.type]]
directory = "removed"
name = "🔥 Removed"
showcontent = true