# generated by datamodel-codegen:
#   filename:  spec.yaml
#   timestamp: 2021-10-05T02:39:37+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Tarefa(BaseModel):
    todo: str
    status: Optional[str] = None


class Tarefas(BaseModel):
    tarefas: List[Tarefa]


class ErrorResponse(BaseModel):
    message: Optional[str] = None


class NotFoundError(BaseModel):
    message: Optional[str] = None
