"""campo idade na pessoa2

Revision ID: b723047f6d98
Revises: 4c23117c5483
Create Date: 2022-07-18 23:14:38.859056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b723047f6d98'
down_revision = '4c23117c5483'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa2', sa.Column('idade', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoa2', 'idade')
    # ### end Alembic commands ###
