pokes = [
    'Bulbasaur',
    'Charmander',
    'Squirtle',
    'Pikachu',
    'Clefairy',
    'Vulpix',
    'Jigglypuff',
    'Zubat',
    'Geodude',
    'Paras',
    'Diglett',
    'Meowth',
    'Psyduck',
    'Mankey',
    'Growlithe',
    'Poliwag',
    'Abra',
    'Machop',
    'Bellsprout',
    'Tentacool',
    'Ponyta',
    'Slowpoke',
    'Magnemite',
    'Farfetchd',
    'Doduo',
    'Seel',
    'Grimer',
    'Shellder',
    'Gastly',
    'Onix',
    'Drowzee',
    'Krabby',
    'Exeggcute',
    'Cubone',
    'Lickitung',
    'Koffing',
    'Rhyhorn',
    'Chansey',
    'Tangela',
    'Horsea',
    'Goldeen',
    'Staryu',
    'Scyther',
    'Jynx',
    'Electabuzz',
    'Magmar',
    'Eevee',
    'Dratini',
    'Chikorita'
]

print('Total de pokemons', len(pokes))

pokes = [x.lower() for x in pokes]
