[project]
name = "live-301"
version = "0.1.0"
description = ""
authors = [
    {name = "dunossauro",email = "mendesxeduardo@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "gunicorn (>=23.0.0,<24.0.0)",
    "uvicorn (>=0.37.0,<0.38.0)",
    "granian (>=2.5.5,<3.0.0)",
    "asgiref (>=3.10.0,<4.0.0)",
    "timing-asgi (>=0.3.1,<0.4.0)",
    "pytest (>=8.4.2,<9.0.0)",
    "httpx[http2] (>=0.28.1,<0.29.0)",
    "pytest-asyncio (>=1.2.0,<2.0.0)",
    "a2wsgi (>=1.10.10,<2.0.0)",
    "starlette (>=0.48.0,<0.49.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
