[project]
name = "live-pbt"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "pytest (>=8.3.5,<9.0.0)",
    "hypothesis (>=6.130.4,<7.0.0)",
    "hypofuzz (>=25.3.3,<26.0.0)",
    "faker (>=37.1.0,<38.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "pydantic (>=2.10.6,<3.0.0)",
    "sqlalchemy (>=2.0.39,<3.0.0)",
    "fastapi[standard] (>=0.115.12,<0.116.0)",
    "harlequin[sqlite] (>=2.1.1,<3.0.0)"
]

[tool.poetry]
packages = [{include = "live_pbt", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
