from httpx import get,post
KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCDFk=print
KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkDF='dunossauro'
KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkDo='meu_segrdo_123'
class KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCDko:
 def __init__(KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkFD):
  KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkFD.atributo=7
 def KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkoD(KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkFD):
  return KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkFD.atributo
def KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkoF():
 KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkFo=get('http://google.com')
 return KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkFo
def KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCDkF(user,passw):
 KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkFo=post('http://meusite.com',json={'password':passw,'username':user})
 return KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkFo
KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCDFk(KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkoF())
KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCDFk(KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCDkF(KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkDF,KMcbLdesIhpqaHjnBNuvlOYmyASfQTPWVXtEJirGxgRUzwCkDo))
# Created by pyminifier (https://github.com/liftoff/pyminifier)

