# generated by fastapi-codegen:
#   filename:  spec.yaml
#   timestamp: 2021-10-05T02:44:59+00:00

from __future__ import annotations

from fastapi import FastAPI, Path
from pydantic import conint

from models import Tarefa, Tarefas

app = FastAPI(
    title='Minha Api de tarefas a fazer',
    version='1.0.0',
)


@app.post('/tarefa', response_model=None)
def post_tarefa(
        tarefa: Tarefa
) -> None:
    """
    Cria uma tarefa
    """
    pass


@app.get(
    '/tarefa', response_model=Tarefas
)
def get_tarefa() -> Tarefas:
    """
    Pega todas as tarefas
    """
    return {'tarefas': [
        Tarefa(todo='batatinha', status='todo'),
        Tarefa(todo='xpto', status='doing'),
    ]}


@app.get('/tarefa/{id}', response_model=None)
def get_tarefa_id(id: conint(ge=1)) -> None:
    pass


@app.patch('/tarefa/{id}', response_model=None)
def patch_tarefa_id(
    tarefa: Tarefa,
        id: conint(ge=1) = ...
) -> None:
    pass


@app.delete('/tarefa/{id}', response_model=None)
def delete_tarefa_id(id: conint(ge=1)) -> None:
    pass
