# Generated by Django 2.2.2 on 2019-06-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='live',
            options={'ordering': ('number',), 'verbose_name': 'live', 'verbose_name_plural': 'lives'},
        ),
        migrations.AddField(
            model_name='live',
            name='number',
            field=models.IntegerField(default=1, verbose_name='número'),
            preserve_default=False,
        ),
    ]
